### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by kim82**
* GoPro Camera(s): Hero 3
* Tested on: Hero 3+ silver
* Firmware version:

### CODE REVIEW

**Comment by KonradIT** [comment]
[Line 61](https://github.com/KonradIT/goprowifihack/pull/35/files#diff-aaccc7b9014bb62fde72e0192bd3b792R61) has resolutions that do not correspond to the camera tested, in this case the Hero3+Silver, I will test it with the HERO3 Black. What are your sources?

**Comment by silent3rror** [comment]
@KonradIT I already have all of the data for the tables for the HERO3 series cameras, so I just need a couple days to format it into tables and tidy it up.

**Comment by silent3rror** [comment]
@KonradIT I found a bunch of archives from gopro's website, dating back to 1996, so i'll work on the HERO2 after I finish the HERO3

**Comment by silent3rror** [comment]
@kim82 @KonradIT #36

**Comment by kim82** [comment]
I got it from the Javascript file from the official Peeble GoPro app.
https://dl.dropboxusercontent.com/u/2014237/pebble-js-app.js

**Comment by KonradIT** [comment]
@kim82 Thanks, I will add some details referencing to the Framerate/Resolution table, by the way, have you started adding other GoPro models support to your pebble app?? I am waiting till I get my pebble

@silent3rror Thanks for adding the HERO3/3+, gonna do HERO2. 

On a relevant note, a HERO+/HERO+LCD camera is needed to grab some commands and camera status JSON, if anyone with that camera wants to contribute just message me or write a issue

**Comment by kim82** [comment]
No, I have not starting adding support for other GoPro models. I've been busy, so I havn't had the time to code it yet.

**Comment by KonradIT** [comment]
@kim82 I see, will add HERO4/3 compatibility in June hopefully

**Pull request merged**
