### PR TITLE
Adding Hero 5 Black pairing commands

### PR DESCRIPTION
**Pull request by p4r4d0x86**
* GoPro Camera(s): Hero 5 Black
* Tested on: Hero 5 Black (and then with Windows 10)
* Firmware version: 02.60

Commands come from official GoPro App
(airmon, airodump & wireshark are our friends :) )

### CODE REVIEW

**Comment by KonradIT** [comment]
Hi, thanks for the PR, this does not make any difference as you can [pair]() your camera to a non-gopro app service and it will work, if you pair it to the GoPro app for the first time and then use the Wifi connection with the URLs it will continue to work, this is so the GoPro can display the device name which is not necessary.

**Comment by p4r4d0x86** [comment]
Hi,
I understand ; I just did this "reverse" because one of my friends tries to build a third-party application and get disconnected after around 3 minutes ... like the pairing delay.
After testing, it seems there is no proprietary "keep alive". I was thinking about a pairing problem.
Kind regards,
Nico

**Comment by KonradIT** [comment]
@p4r4d0x86 yes, to keep the GoPro alive send this magic packet every few seconds: _GPHD_:0:0:2:0.000000\n

**Comment by p4r4d0x86** [comment]
@KonradIT Indeed, now I see the UDP packet on port 8554 : _GPHD_:0:0:2:0.000000.
Thank you a lot for letting me know that :)

Kind regards,
Nico

**Comment by Micro16** [comment]
Hi,

@KonradIT  I send udp packets on ports 8554 with "_GPHD_:0:0:2:0.000000\n" and it does not work.
I get disconnected after approximately 10 minutes. 

How do i have to setup the udp packets in order to keep the connection alive ? 

Thanks !

**Pull request closed without merging**
