### PR TITLE
Update WifiCommands.md

### PR DESCRIPTION
**Pull request by john-arvid**
* GoPro Camera(s): Hero3+Black
* Tested on: Hero3+Black
* Firmware version: v03.03

Added an example to the camera TM.
Is this ok?

### CODE REVIEW

**Comment by silent3rror** [comment]
Check line 53 again `%10%05%0b%10%2f%31` 
If your example time is 2016-05-11 16:47:49, the correct format if i'm not mistaken would be `%16%05%11%16%47%49`

**Comment by john-arvid** [comment]
With firmware v03.03 they are using hex instead of integers. So in my case, Hero3+Black v03.03 line 53 is correct. Maybe this info could be added with that note?

**Comment by silent3rror** [comment]
In that case, yes a note that hex is used to express the integers in the string

**Comment by john-arvid** [comment]
would that latest change be ok?

**Comment by silent3rror** [comment]
Can you provide a `JSON` file showing the output of the time in hex?

**Comment by john-arvid** [comment]
Could you elaborate?
Do I get this JSON file from the Gopro? (Maybe not in that format, but where do I get that data?)

**Comment by silent3rror** [comment]
As in providing the output of the GoPro after running the `CAMERA TM` command

**Comment by john-arvid** [comment]
I'm testing in powershell. (Don't hit me)

The content received when sending this to the GoPro %10%05%0b%12%0f%38
is
0
16
5
11
18
15
56

Were not sure how to format this to JSON

**Comment by silent3rror** [comment]
Okay, I see where the failure point is. The output of the command is decimal, not ASCII / ANSI formatting, so if you were to convert `16 5 11 18 15 56` to hex, the result would be `31 36 20 35 20 31 31 20 31 38 20 31 35 20 35 36`. That being said, you'd need to convert decimal to hexadecimal. `16 5 11 18 15 56` expressed in hexadecimal is ` 10 05 0b 12 0f 38`

**Comment by silent3rror** [comment]
Be sure to write a note, along the lines of converting decimal to hexadecimal

**Comment by john-arvid** [comment]
Not quite sure what you meant, but I have tried to simplify it.
Is this ok?

**Comment by silent3rror** [comment]
That will do, but I suggest you refer to https://github.com/silent3rror/goprowifihack/tree/patch-8/HERO3

**Comment by silent3rror** [comment]
#38

**Comment by KonradIT** [comment]
Also, will add a link to @silent3rror's numeric table.

**Comment by silent3rror** [comment]
@KonradIT minor changes to save confusion #39

**Pull request merged**
