### PR TITLE
Add HERO 9 LiveStreaming

### PR DESCRIPTION
**Pull request by Dixiao-L**
* GoPro Camera(s): Hero 9
* Tested on: Hero 9
* Firmware version: 01.52

I guess this feature does not belong to the GoPro-Connect.md, it is simply the feature "Preview" in the "GoPro Quik" app.

So the file GoPro-Connect.md is left unchanged.

### CODE REVIEW

**Comment by DechengMa** [comment]
@Dixiao-L Thank you for your awesome work! 
After I set up the live stream thing on my HERO9, the video is completed corrupted, I wonder if you know how to fix it? 
image
If possible, may I know what system are you using? Windows or Mac?
Thanks in advance!

**Comment by Dixiao-L** [comment]
> @Dixiao-L Thank you for your awesome work! 
> After I set up the live stream thing on my HERO9, the video is completed corrupted, I wonder if you know how to fix it? 
> image
> If possible, may I know what system are you using? Windows or Mac?
> Thanks in advance!

I did came to this when using Potplayer on windows, however Linux (I tested on Debian) seems to behave pretty well. Personally, I tend to believe this is caused by decoder, because the UDP package doesn't appear abnormally.
Wish you get rid of it soon!

**Comment by DechengMa** [comment]
@Dixiao-L Thanks for your quick reply 🙏  , could you please tell me which player are you using on Linux? I am using the VLC player on a Mac but it doesn't work 🤔

**Comment by Dixiao-L** [comment]
> @Dixiao-L Thanks for your quick reply 🙏  , could you please tell me which player are you using on Linux? I am using the VLC player on a Mac but it doesn't work 🤔 

Just ffplay.

**Pull request merged**
