### PR TITLE
Updated CameraStatus.md and WifiCommands.md

### PR DESCRIPTION
**Pull request by networkjanitor**
* GoPro Camera(s): HERO4 Silver
* Tested on: HERO4 Silver, 2016-07-03
* Firmware version: HD4.01.03.00.00

### CODE REVIEW

**Comment by KonradIT** [comment]
I don't have a HERO4 Silver with me, @silent3rror can you test?

**Comment by networkjanitor** [comment]
Sorry for the mess, figured that multiple pull requests for multiple changes would be the easiest to handle - but github didnt work in the way I expected it to work in.

**Comment by KonradIT** [comment]
Cool! I will merge bith and let @silent3rror do the testing afterwards and correct any mistakes.

**Comment by silent3rror** [comment]
Tested in the car on the way up north on my phone as I do not have my computer. Everything in the pull looks good.. Tested all the HTTP GET URL's and everything works perfectly. I also tried the before and after commands to make sure that when I used the wrong url, that I got an error, and when I used the right one `{}` was the returned output. - Sent on my Motorola Droid Ultra

**Comment by KonradIT** [comment]
@silent3rror yep, that confirms that these are correct URLs, can you also test #44?

**Pull request merged**
